### ISSUE TITLE
have you met grid pattern in raw denoising training? 

### ISSUE THREAD

**Issue by dididadida** [demonsjin/Blind2Unblind#10]

**Comment by dididadida** [comment]
could not fix this by tuning parameters in losses.

**Comment by zejinwang** [comment]
I can't understand what your problem is, please explain in detail.

**Comment by dididadida** [comment]
![image](https://user-images.githubusercontent.com/48912660/226327209-b7aad42e-04e7-4f80-b78e-632dbb98facc.png)
![image](https://user-images.githubusercontent.com/48912660/226327316-c375171d-1360-4ca8-abde-5f23164d943e.png)
第一个是输入，第二个是输出。基于我自己的数据训的。测试的时候，图片过完模型长这样，模型没收敛（训练越久越奇怪）。是得怎么微调那些训练参数呢？

**Comment by zejinwang** [comment]
raw域噪声数据训练时需要按照bayer阵列进行展开，由单通道变成四通道，请注意下这个细节

**Comment by dididadida** [comment]
是展开了的，但就是训的很奇怪。把你的模型和masker缝合到我的代码里训不出一个收敛的。但是我自己的代码训n2n没问题。我直接用你训练好的权重测试我的数据也没异常

**Comment by zejinwang** [comment]
可以关注下这三个点，分别是学习率设置；训练新数据集的梯度稳定性以及代码迁移可能存在问题（重点关注下masker操作）。你可以直接在我提供的源码上训练看下是否有这个问题
