### ISSUE TITLE
Applying to a general image restoration

### ISSUE THREAD

**Issue by rose-jinyang** [demonsjin/Blind2Unblind#18]
Hello
How are you?
Thanks for contributing to this project.
It seems that this method is customized for ONLY denoising.
Is it possible to apply this method without any change to a general image restoration tasks such as image deblurring & deraining?

**Comment by zejinwang** [comment]
Perhaps this is the paper [Self-Supervised Image Restoration
with Blurry and Noisy Pairs](https://proceedings.neurips.cc/paper_files/paper/2022/file/bc12914d66b41b6bfc2d3a5decdb498b-Paper-Conference.pdf) you're looking for. I believe it can provide you with some inspiration.
