### ISSUE TITLE
The loss increases with training, please help！

### ISSUE THREAD

**Issue by xuthreekid** [demonsjin/Blind2Unblind#19]
损失随着训练而增加，最终的图像去噪效果显示规则的条纹形状。

<img width="685" alt="截屏2023-07-14 21 02 38" src="https://github.com/zejinwang/Blind2Unblind/assets/81002297/3aedff50-4ed4-4930-8548-7977660806c1">

**Comment by zejinwang** [comment]
"I suspect that the noise in your data may have strong spatial correlation, and this method is primarily targeted at pixel-independent noise. For single-channel grayscale images, adding TV loss can effectively solve the problem you are facing."

**Comment by xuthreekid** [comment]
Thanks for you reply! I will give it a try!

**Comment by yashkhurana24** [comment]
@lvxuzijian what denoising method worked for you?
