### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by huanzheng551803** [demonsjin/Blind2Unblind#2]
why adding noise each iteration on Guassian case? I think it should be only adding once and training with them.

**Comment by demonsjin** [comment]
The same noise level generates non-deterministic noise, therefore it must be regenerated every time it is created.

**Comment by zejinwang** [comment]
> why adding noise each iteration on Guassian case? I think it should be only adding once and training with them.

The same noise level generates non-deterministic noise, therefore it must be regenerated every time it is created.

**Comment by huanzheng551803** [comment]
then the problem become supervised training. Since we can get the same image with different noise.

Also in real case, we can not access the same image with different noise

**Comment by demonsjin** [comment]
> then the problem become supervised training. Since we can get the same image with different noise.
> 
> Also in real case, we can not access the same image with different noise

Maybe

> then the problem become supervised training. Since we can get the same image with different noise.
> 
> Also in real case, we can not access the same image with different noise

Maybe you have some mistakes in understanding the code.

**Comment by zejinwang** [comment]
Maybe you have some mistakes in understanding the code.

**Comment by huanzheng551803** [comment]
its not about the code,but about the problem setting

In unsupervised denoising, unsupervised means we have no clean image, only noisy image itself.
But if you add noise every iteration, it means we can access the clean image by averaging them, this does not meet the problem setting

**Comment by zejinwang** [comment]
Since the loss function does not include clean images and only uses noisy images, our method is fully self-supervised.

**Comment by huanzheng551803** [comment]
i admit your method is fully self-supervised. But  i think the experiment should mimic the real case, where we only have one noisy image for each image

**Comment by zejinwang** [comment]
No noise is added to SIDD or FMDD images; instead, we train directly on raw noisy images.
