### ISSUE TITLE
How to prepare ValidationNoisyBlocksRaw.mat for SIDD RAW training?

### ISSUE THREAD

**Issue by visibh** [demonsjin/Blind2Unblind#6]
Thank you for the great work but can you please provide some code/pointer on how to prepare ValidationNoisyBlocksRaw.mat which is required for validation for SIDD RAW denoising?

**Comment by visibh** [comment]
Files can be downloaded from here:
https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php

**Comment by tianshukai99** [comment]
Hi, how do I turn my own dataset into ValidationNoisyBlocksRaw.mat and ValidationGtBlocksRaw.mat when I train it directly on my own dataset? However after I run python train_sidd_b2u.py --data_dir . /data/train/SIDD_Medium_Raw_noisy_sub512 --val_dirs . /data/validation ---save_model_path . /experiments/results --log_name b2u_unet_raw_112rf20 --Lambda1 1.0 --Lambda2 2.0 --increase_ratio 20.0 Command Times Error Expecting miMATRIX type here, got 16843009, can you please help me? Really appreciate it!!!
