### ISSUE TITLE
代码使用请教

### ISSUE THREAD

**Issue by Mrhard1999** [demonsjin/Blind2Unblind#9]
请问您这个代码有专用的数据集吗？如果有能否提供数据集链接？或者说用含有噪声的图片就可完成训练？

**Comment by zejinwang** [comment]
用噪声数据集即可完成训练，只需要保证数据集的噪声满足泊松高斯分布。如果要用公开数据集进行训练，可以使用SIDD数据集，链接为：https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php。
